version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: bitnami/wordpress:6.1.1
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - wordpress_data:/bitnami/wordpress
    environment:
      WORDPRESS_DATABASE_HOST: db
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 512M
      PHP_UPLOAD_MAX_FILESIZE: 512M
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: |
        /* wp-config.phpに設定を追記するときはここに追加してください */
        define('WP_AUTO_UPDATE_CORE', true);

volumes:
  wordpress_data:
  db_data: